# Generated by Django 3.0 on 2019-12-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.BigIntegerField(db_column='osm_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'planet_osm_point',
            },
        ),
    ]
