version: '3'

volumes: 
    osm-data:

services:
    api:
        build: 
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - "80:80"
        tty: true
    db:
        image: mdillon/postgis
        restart: unless-stopped
        environment: 
            - POSTGRES_PASSWORD=admin
        volumes: 
            - osm-data:/osm-data